# This file can be included in your hass configuration.yaml 
# add the below in the "homeassistant:" section
#  
#  packages: 
#    kiota_kitchen: !include /home/pi/working/kiota/devices/example_DHTDevice.yaml

sensor:

  - name: "Example Temperature"
    platform: mqtt
    state_topic: "/devices/example/temperature_and_humidity_sensor"
    qos: 0
    unit_of_measurement: "°C"
    value_template: '{{ value_json.temperature }}'  

  - name: "Example Humidity"
    platform: mqtt
    state_topic: "/devices/example/temperature_and_humidity_sensor"
    qos: 0
    unit_of_measurement: "%"
    value_template: '{{ value_json.humidity }}'  
